name: CI/CD K8sPSDrive


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install k8s
      run: |
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
        cat /etc/rancher/k3s/k3s.yaml
        mkdir -p ~/.kube
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      uses: cake-build/cake-action@v1
      with:
        target: build
    - name: Test
      uses: cake-build/cake-action@v1
      with:
        target: test
    - name: Publish
      uses: cake-build/cake-action@v1
      with:
        target: publish
        configuration: release
    - name: Update diagram
      uses: githubocto/repo-visualizer@main
      with:
        excluded_paths: "ignore,.github"